Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/addons/base/models/ir_ui_view.py", line 394, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/addons/base/models/ir_ui_view.py", line 987, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: Field `instructor` does not exist

Error context:
View `partner.instructor`
[view_id: 836, xml_id: n/a, model: res.partner, parent_id: 121]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/tools/convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/models.py", line 4080, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/models.py", line 3994, in _load_records_create
    return self.create(values)
  File "<decorator-gen-31>", line 2, in create
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/addons/base/models/ir_ui_view.py", line 475, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/models.py", line 3775, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/fields.py", line 1120, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/addons/base/models/ir_ui_view.py", line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/models.py", line 3564, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/models.py", line 1176, in _validate_fields
    check(self)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/addons/base/models/ir_ui_view.py", line 396, in _check_xml
    raise ValidationError("%s\n\n%s" % (_("Error while validating view"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating view\n\nField `instructor` does not exist\n\nError context:\nView `partner.instructor`\n[view_id: 836, xml_id: n/a, model: res.partner, parent_id: 121]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-65>", line 2, in button_immediate_upgrade
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/addons/base/models/ir_module.py", line 634, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/modules/loading.py", line 419, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/modules/loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/tools/convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/tools/convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/tools/convert.py", line 721, in parse
    exc_info[2]
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/tools/convert.py", line 577, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/models.py", line 4080, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/models.py", line 3994, in _load_records_create
    return self.create(values)
  File "<decorator-gen-31>", line 2, in create
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/addons/base/models/ir_ui_view.py", line 475, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/api.py", line 336, in _model_create_multi
    return create(self, arg)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/models.py", line 3775, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/fields.py", line 1120, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/addons/base/models/ir_ui_view.py", line 493, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/models.py", line 3564, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/models.py", line 1176, in _validate_fields
    check(self)
  File "/home/dmprabath/Codeso/odoo/odoo-13.0/odoo/addons/base/models/ir_ui_view.py", line 396, in _check_xml
    raise ValidationError("%s\n\n%s" % (_("Error while validating view"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating view

Field `instructor` does not exist

Error context:
View `partner.instructor`
[view_id: 836, xml_id: n/a, model: res.partner, parent_id: 121]
None" while parsing /home/dmprabath/Codeso/odoo/odoo-13.0/addons/openacademy/views/partner.xml:2, near
<odoo>

        <!-- Add instructor field to existing view -->
        <record model="ir.ui.view" id="partner_instructor_form_view">
            <field name="name">partner.instructor</field>
            <field name="model">res.partner</field>
            <field name="inherit_id" ref="base.view_partner_form"/>
            <field name="arch" type="xml">
                <notebook position="inside">
                    <page string="Sessions">
                        <group>
                            <field name="instructor"/>
                            <field name="session_ids"/>
                        </group>
                    </page>
                </notebook>
            </field>
        </record>

        <record model="ir.actions.act_window" id="contact_list_action">
            <field name="name">Contacts</field>
            <field name="res_model">res.partner</field>
            <field name="view_mode">tree,form</field>
        </record>
        <menuitem id="configuration_menu" name="Configuration" parent="main_openacademy_menu"/>
        <menuitem id="contact_menu" name="Contacts" parent="configuration_menu" action="contact_list_action"/>

</odoo>
